/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-118328-g504df09c34-20250120"
#endif /* AVUTIL_FFVERSION_H */
